In [1]:
import numpy as np

In [2]:
#numpy types
datatype=np.dtype(np.int32)
print(datatype)

int32


In [3]:
dt1=np.dtype('i4')
dt2=np.dtype('i1')
dt3=np.dtype('i2')
dt4=np.dtype('i8')
print(dt1,dt2,dt3,dt4,sep='\n')

int32
int8
int16
int64


In [4]:
#endian notation
end=np.dtype('>i8')
print(end)

>i8


In [5]:
#numpy data types
k=np.bool
m=np.int
n=np.float
p=np.short
q=np.byte
r=np.longlong
s=np.double
t=np.cdouble
u=np.csingle
v=np.single
print(k,m,n,p,q,r,s,t,u,v,sep='\n')

<class 'bool'>
<class 'int'>
<class 'float'>
<class 'numpy.int16'>
<class 'numpy.int8'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.float32'>


In [6]:
print(np.array([1,2,34,-5],dtype='i'))
print(np.array([1,2,34,-5],dtype='f'))
print(np.array([1,2,34,-5],dtype=np.uint64))#unsigned integer 64 bits
print(np.array([1,2,34,-5],dtype=np.int64))
print(np.array([1,2,34,-5],dtype='c'))#doubt



[ 1  2 34 -5]
[ 1.  2. 34. -5.]
[                   1                    2                   34
 18446744073709551611]
[ 1  2 34 -5]
[b'1' b'2' b'3' b'-']


In [7]:
#conversion of dtype of an array
type1=np.dtype(np.uint32)#unsigned integer
abc1=np.array([(30.4),(44.98),(-45.98)])
abc=np.array([(30.4),(44.98),(-45.98)],dtype=type1)
print(abc1,abc,sep='\n')

[ 30.4   44.98 -45.98]
[        30         44 4294967251]


In [8]:
ap=np.array([55.9875467,8875653,98676542],dtype=np.int32)
print(type(ap))
print(ap.dtype)
print(np.float32(ap))
print(np.cdouble(ap))#c-complex
print(ap.astype(np.single))#single-float32
l=ap.astype(np.single)
print(l.dtype)

<class 'numpy.ndarray'>
int32
[5.500000e+01 8.875653e+06 9.867654e+07]
[5.5000000e+01+0.j 8.8756530e+06+0.j 9.8676542e+07+0.j]
[5.500000e+01 8.875653e+06 9.867654e+07]
float32


In [9]:
#numpy arrays
a=np.array([23,78,97,-9,-2,-66.989])
print(a,a.dtype,sep='\n')

[ 23.     78.     97.     -9.     -2.    -66.989]
float64


In [10]:
b=np.array([[12,98,876.98],[98,76,-75]])
print(b)

[[ 12.    98.   876.98]
 [ 98.    76.   -75.  ]]


In [11]:
c=np.array([[[34,87,9778,7764,643212,970856],[87545,9864,98,9886],
           [8755,867,0.98,987,-9]]],ndmin=2)
print(c)

[[list([34, 87, 9778, 7764, 643212, 970856])
  list([87545, 9864, 98, 9886]) list([8755, 867, 0.98, 987, -9])]]


In [12]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [16]:
np.linspace(4,10,5)

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

In [17]:
print(np.array([[20,98.76,-67,-763],('hey',98.08)]))
      
print(np.array([20,98.76,-67,-763],dtype=int))

[list([20, 98.76, -67, -763]) ('hey', 98.08)]
[  20   98  -67 -763]


In [18]:
sh=np.array([34,98.87,0.98])
print(sh.dtype)

float64


In [19]:
k=np.array([[[34,90,678,0.987,-0.99],['67','54','644.00'],['hey','good','hello']]])
print(k.shape)
print(k.reshape(3,1))

(1, 3)
[[list([34, 90, 678, 0.987, -0.99])]
 [list(['67', '54', '644.00'])]
 [list(['hey', 'good', 'hello'])]]


In [20]:

shi=np.array([[[34,90,678,987,99],[67,54,644],[56,12,30]]])
print(shi)
print(shi.shape)
print(shi.reshape(3,1))


[[list([34, 90, 678, 987, 99]) list([67, 54, 644]) list([56, 12, 30])]]
(1, 3)
[[list([34, 90, 678, 987, 99])]
 [list([67, 54, 644])]
 [list([56, 12, 30])]]


In [21]:
m=np.arange(-10,130,9)
print(m)
print(len(m))

[-10  -1   8  17  26  35  44  53  62  71  80  89  98 107 116 125]
16


In [22]:
print(m.reshape(4,4))
print(m.reshape(8,2))

[[-10  -1   8  17]
 [ 26  35  44  53]
 [ 62  71  80  89]
 [ 98 107 116 125]]
[[-10  -1]
 [  8  17]
 [ 26  35]
 [ 44  53]
 [ 62  71]
 [ 80  89]
 [ 98 107]
 [116 125]]


In [23]:
nim=np.arange(63)
nim.reshape(3,3,7)

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]],

       [[42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62]]])

In [24]:
print(nim.size)#no.of elements in the array
print(nim.shape)
print(nim.ndim)#no.of dimensions of the array
print(nim.itemsize)#no.of bytes for each value 
print(nim.nbytes)#total no.of bytes for all the values

63
(63,)
1
4
252


In [25]:
nim[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62])

In [26]:
y=np.random.randint(18,size=(9,2))
print(y.ndim,"\n")
print(y,y.reshape(2,9),sep="\n ")
print(y[2:,1:],"\n")

2 

[[11 11]
 [ 6 11]
 [10  5]
 [ 3  9]
 [ 2  3]
 [17 14]
 [ 0  3]
 [ 5 16]
 [17 17]]
 [[11 11  6 11 10  5  3  9  2]
 [ 3 17 14  0  3  5 16 17 17]]
[[ 5]
 [ 9]
 [ 3]
 [14]
 [ 3]
 [16]
 [17]] 



In [27]:
x=np.random.randint(27,size=(3,4,5))
print(x,"\n")
print(x.ndim,"\n")
print(x[0:1,1:2,-3:-1],"\n")
print(x[1:,2:,3:])

[[[ 0  1  9  0  4]
  [22  9 24  8  3]
  [13 15 25  2  0]
  [10 19 17 12 11]]

 [[22  9  9 26 17]
  [15  3 12 22 14]
  [20 21  7  0 11]
  [25 24 26 11  2]]

 [[16  9 23 10 16]
  [ 4  2 16 23 10]
  [18  7 12 26 23]
  [ 2 19 23 23 17]]] 

3 

[[[24  8]]] 

[[[ 0 11]
  [11  2]]

 [[26 23]
  [23 17]]]


In [28]:
help(slice)

Help on class slice in module builtins:

class slice(object)
 |  slice(stop)
 |  slice(start, stop[, step])
 |  
 |  Create a slice object.  This is used for extended slicing (e.g. a[0:10:2]).
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  indices(...)
 |      S.indices(len) -> (start, stop, stride)
 |      
 |      Assuming a sequence of length len, calculate the start and stop
 |      indices, and the stride length of the extended slice des

In [29]:
import math as ma

In [30]:
ma.sqrt(76)

8.717797887081348

In [31]:
ma.pow(4,4)

256.0

In [32]:
ma.floor(76.98866)

76

In [33]:
ma.ceil(-8665.976)

-8665

In [34]:
print("sine value-math lib",ma.sin(67))
print("cosine value-math lib",ma.cos(180))
print("tan value-math lib",ma.tan(187))
print("hyperbolic sine value-math lib",ma.sinh(-0.855))
print("Inverse sine-numpy in array",np.arcsin([1,0.2,0.8]))
print("Hyperbolic tan value(math)-math lib",ma.tanh(87))
print("Hyperbolic tan(numpy) ",np.tanh(87))
print("Inverse tan-numpy in array",np.arctanh([0.1,0.2,0.8]))


sine value-math lib -0.8555199789753223
cosine value-math lib -0.5984600690578581
tan value-math lib -13.26622453436095
hyperbolic sine value-math lib -0.9630455947463139
Inverse sine-numpy in array [1.57079633 0.20135792 0.92729522]
Hyperbolic tan value(math)-math lib 1.0
Hyperbolic tan(numpy)  1.0
Inverse tan-numpy in array [0.10033535 0.20273255 1.09861229]


In [35]:
p=np.array([3,4,5])
q=np.array([6,7,5])
res=((q-p)**2).sum()
print(q-p)
print((q-p)**2)
print(res)
print(ma.sqrt(res))

[3 3 0]
[9 9 0]
18
4.242640687119285


In [36]:
np.deg2rad(45)

0.7853981633974483

In [37]:
np.rad2deg(0.985)

56.43634282038609

In [38]:
np.degrees(57)

3265.8594322456925

In [39]:
np.around([87.87456,-32.98,-56.090])

array([ 88., -33., -56.])

In [40]:
a=np.array([-0.78,.17,30.98,-.78,98.0002])

In [41]:
print(a)
print("truncate of the above array",np.trunc(a),"\n")
print("fix of the above array",np.fix(a),"\n")
print("rint of the above array",np.rint(a),"\n")

[-0.78    0.17   30.98   -0.78   98.0002]
truncate of the above array [-0.  0. 30. -0. 98.] 

fix of the above array [-0.  0. 30. -0. 98.] 

rint of the above array [-1.  0. 31. -1. 98.] 



In [42]:
x=np.array([1,2,3,4,7])
print(np.log2(x),"\n")
print(np.log10(x),"\n")
print(np.exp2(x),"\n")

[0.         1.         1.5849625  2.         2.80735492] 

[0.         0.30103    0.47712125 0.60205999 0.84509804] 

[  2.   4.   8.  16. 128.] 



In [43]:
ab=np.arange(10)
bc=np.arange(10)
print(ab)
print(np.sum(ab))
print(np.multiply(ab,bc))
print(np.floor_divide(ab[1:],bc[1:]))
print(np.divmod(ab,5),sep="\n")
print(np.maximum(65,-878))
ki=np.array([-90,-765,0.9,1.34,9.8])
print(np.fabs(ki))
print(np.square(ab))

[0 1 2 3 4 5 6 7 8 9]
45
[ 0  1  4  9 16 25 36 49 64 81]
[1 1 1 1 1 1 1 1 1]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int32))
65
[ 90.   765.     0.9    1.34   9.8 ]
[ 0  1  4  9 16 25 36 49 64 81]


In [44]:
a=np.array([99,78,65,31])
b=np.array([45,10,17,23])
print(a+b,a-b,a*b,a*4,sep="\n")

[144  88  82  54]
[54 68 48  8]
[4455  780 1105  713]
[396 312 260 124]


In [51]:
from scipy import stats
print(a,"mean of a:",np.mean(a),"\n")
print(b,"median of b",np.median(b),"\n")
print("mode of [2,2,4,5,6,77,77,12,77,88,99]",stats.mode([2,2,4,5,6,77,77,12,77,88,99]))

[99 78 65 31] mean of a: 68.25 

[45 10 17 23] median of b 20.0 

mode of [2,2,4,5,6,77,77,12,77,88,99] ModeResult(mode=array([77]), count=array([3]))
